// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXL6-wmie9hZTMm6hoR3iNwLQXCLSNmp8',
    appId: '1:415918460866:web:c0222d1cae76b09448905b',
    messagingSenderId: '415918460866',
    projectId: 'socialsnap-30aef',
    authDomain: 'socialsnap-30aef.firebaseapp.com',
    storageBucket: 'socialsnap-30aef.firebasestorage.app',
    measurementId: 'G-Z1NGFXH8C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVwRa-MsSDemCjWSXAN4BUQ-Gd5m7aFQ',
    appId: '1:415918460866:android:aa9730298693ed5948905b',
    messagingSenderId: '415918460866',
    projectId: 'socialsnap-30aef',
    storageBucket: 'socialsnap-30aef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUtrZm5D35msTG7TLmHdBR12NKEHy3Aw',
    appId: '1:415918460866:ios:677feaee6f79846c48905b',
    messagingSenderId: '415918460866',
    projectId: 'socialsnap-30aef',
    storageBucket: 'socialsnap-30aef.firebasestorage.app',
    iosBundleId: 'com.example.socialSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUtrZm5D35msTG7TLmHdBR12NKEHy3Aw',
    appId: '1:415918460866:ios:677feaee6f79846c48905b',
    messagingSenderId: '415918460866',
    projectId: 'socialsnap-30aef',
    storageBucket: 'socialsnap-30aef.firebasestorage.app',
    iosBundleId: 'com.example.socialSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXL6-wmie9hZTMm6hoR3iNwLQXCLSNmp8',
    appId: '1:415918460866:web:951c5c051033b36148905b',
    messagingSenderId: '415918460866',
    projectId: 'socialsnap-30aef',
    authDomain: 'socialsnap-30aef.firebaseapp.com',
    storageBucket: 'socialsnap-30aef.firebasestorage.app',
    measurementId: 'G-4B70LSPP1E',
  );
}
